cls_file_str: |-
  \ProvidesClass{PeterlitsNote}
  \LoadClass{ctexbook}

  \RequirePackage[nosfdefault]{sourcesanspro}
  \newcommand{\CONSOLAS}{\sourcesansprolight}

  \newcommand{\code}[1]
      {{\CONSOLAS #1}}
  \newcommand{\timetx}[1]
      {\noindent\emph{\small #1}\vspace{2em}}
  \newcommand{\x}{\textbackslash}

  \renewcommand \thesection {\@arabic\c@section}
  \renewcommand \section{\@startsection {section}{1}{\z@}%
                                        {4em \@plus .5ex \@minus 2ex}%
                                        {.4ex \@plus.1ex}%
                                        {\normalfont\Large\bfseries}}
tex_file_str: |-
  \documentclass{PeterlitsNote}

  \begin{document}
      ***
  \end{document}
file_name: PeterlitsNote
